services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0289
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    dns:
      - 8.8.8.8
      - 8.8.4.4

  spring-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0289
    depends_on:
      postgres:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    depends_on:
      - spring-api
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data: